import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  UserOutline,
  EyeOutline,
  EyeInvisibleOutline,
  LockOutline,
  SearchOutline,
  PlusOutline,
  ArrowLeftOutline,
  CheckCircleTwoTone,
  CloseCircleTwoTone,
  FolderOpenOutline,
  ProductOutline,
  LineChartOutline,
  PhoneOutline,
  FileOutline,
  ShoppingCartOutline,
  StopOutline,
  LogoutOutline,
  DownloadOutline,
  SaveOutline,
  PushpinFill,
  UnlockOutline,
  MenuOutline,
  MailOutline,
  QuestionCircleOutline,
  MailFill,
  EnvironmentFill,
  PhoneFill,
  ClockCircleFill,
  HomeOutline,
  InfoOutline,
  GiftOutline,
  BankOutline, NotificationOutline
} from '@ant-design/icons-angular/icons';

export const icons = [MenuFoldOutline, MenuUnfoldOutline, DashboardOutline, FormOutline, UserOutline, EyeOutline, PhoneOutline, MailOutline, MenuOutline, MailFill, EnvironmentFill,
  PhoneFill, HomeOutline, InfoOutline, BankOutline,
  ClockCircleFill, GiftOutline, NotificationOutline,
  SearchOutline, PlusOutline, EyeInvisibleOutline, LockOutline, ArrowLeftOutline, CheckCircleTwoTone, StopOutline, CloseCircleTwoTone, FolderOpenOutline, ProductOutline, LineChartOutline, FileOutline, ShoppingCartOutline, LogoutOutline, DownloadOutline, SaveOutline, PushpinFill, UnlockOutline, QuestionCircleOutline];
