import { Component, inject, OnInit } from '@angular/core';
import { FormGroup, NonNullableFormBuilder, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { apiService } from '../../services/apiService';

@Component({
  selector: 'app-registration',
  imports: [NzInputModule, NzFormModule, NzCardModule, ReactiveFormsModule, RouterModule, NzButtonModule, NzSelectModule, NzDatePickerModule],
  templateUrl: './registration.component.html',
  styleUrl: './registration.component.scss'
})
export class RegistrationComponent implements OnInit{
  // Form data
  registrationForm!: FormGroup;
  private fb = inject(NonNullableFormBuilder)
  private apiService = inject(apiService)



  ngOnInit(): void {
   this.initilizeForm();
  }

  initilizeForm(){
    this.registrationForm = this.fb.group({
    id: [null],                  // generated by Firebase or backend
    fullName: [null],
    email: [null],
    phone: [null],
    password: [null],      // only if you're handling auth yourself
    bloodGroup: [null] ,         // e.g. 'A+', 'O-', etc.
    age: [null],
    gender: [null],
    phoneprefix: ['+91'],
    isAvailable: [true],  // switch toggle
    dob: [null],    // optional
    city: [null],
    state: [null],
    address: [null],
    role: ['ROLE_ADMIN'],
    latitude: [null],
    longitude: [null],
    });
  }

  submitForm() {
    this.apiService.register(this.registrationForm.value).subscribe((res) => {
      console.log(res);
    });
    console.log('Form submitted:', this.registrationForm.value);
    // Add your registration logic here (e.g., API call)
  }

  onChange(event: any) {
    console.log(event);
  }

  // Ask for location permission on component initialization
  ngAfterViewInit() {
    if (navigator.permissions) {
      navigator.permissions.query({ name: 'geolocation' as PermissionName }).then((result) => {
        if (result.state === 'granted') {
          this.getLocation(); // already allowed
        } else if (result.state === 'prompt') {
          // Trigger prompt, then get location if allowed
          navigator.geolocation.getCurrentPosition(
            (position) => {
              this.registrationForm.patchValue({
                latitude: position.coords.latitude,
                longitude: position.coords.longitude
              });
            },
            (error) => {
              console.warn('User denied location permission:', error);
            }
          );
        } else if (result.state === 'denied') {
          console.warn('Location permission denied. Please enable it in browser settings.');
        }

        // Optional: listen for changes (e.g., user changes permission in browser)
        result.onchange = () => {
          if (result.state === 'granted') {
            this.getLocation();
          }
        };
      });
    } else {
      // Fallback for older browsers
      this.getLocation();
    }
  }
  

  getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          this.registrationForm.patchValue({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude
          });
        },
        (error) => {
          console.error('Geolocation error:', error);
        }
      );
    } else {
      console.error('Geolocation is not supported by this browser.');
    }
  }

}
