import { Component, inject, OnInit } from '@angular/core';
import { FormGroup, NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { apiService } from '../../services/apiService';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { NzModalRef } from 'ng-zorro-antd/modal';

@Component({
  selector: 'app-registration',
  imports: [NzInputModule, NzFormModule, NzCardModule, ReactiveFormsModule, RouterModule, NzButtonModule, NzSelectModule, NzDatePickerModule],
  templateUrl: './registration.component.html',
  styleUrl: './registration.component.scss'
})
export class RegistrationComponent implements OnInit{
  // Form data
  private nominatimUrl = 'https://nominatim.openstreetmap.org/reverse';
  registrationForm!: FormGroup;
  private fb = inject(NonNullableFormBuilder)
  private apiService = inject(apiService)
  private http = inject(HttpClient)
  isEditable:boolean = false;
  constructor(){}
  ngOnInit(): void {
   this.initilizeForm();
  }

  initilizeForm(){
    this.registrationForm = this.fb.group({
    id: [null],                  // generated by Firebase or backend
    fullName: [null, [Validators.required]],
    email: [null, [Validators.required, Validators.email]],
    phone: [null, [Validators.required]],
    password: [null, [Validators.required]],      // only if you're handling auth yourself
    bloodGroup: [null, [Validators.required]] ,         // e.g. 'A+', 'O-', etc.
    age: [null, [Validators.required]],
    gender: [null, [Validators.required]],
    phonePrefix: ['+91'],
    isAvailable: [true, [Validators.required]],  // switch toggle
    dob: [null, [Validators.required]],    // optional
    country: [{ value: null, disabled: true }, [Validators.required]],
    countryCode: [null, [Validators.required]],
    city: [{ value: null, disabled: true }, [Validators.required]],
    state: [{ value: null, disabled: true }, [Validators.required]],
    address: [null],
    role: ['ROLE_USER'],
    latitude: [null,[Validators.required]],
    longitude: [null,[Validators.required]],
    lastDonationDate: [null],
    });
  }

  submitForm() {
    console.log('Form submitted:', this.registrationForm);
    if(this.registrationForm?.valid) {
      this.apiService.register(this.registrationForm.getRawValue()).subscribe((res) => {
        console.log(res);
        window.history.back();
      });
    }
  }

  onChange(event: any) {
    console.log(event);
  }

  // Ask for location permission on component initialization
  ngAfterViewInit() {
    if (navigator.permissions) {
      navigator.permissions.query({ name: 'geolocation' as PermissionName }).then((result) => {
        if (result.state === 'granted') {
          this.getLocation(); // already allowed
        } else if (result.state === 'prompt') {
          // Trigger prompt, then get location if allowed
          navigator.geolocation.getCurrentPosition(
            (position) => {
              this.registrationForm.patchValue({
                latitude: position.coords.latitude,
                longitude: position.coords.longitude
              });
            },
            (error) => {
              console.warn('User denied location permission:', error);
            }
          );
        } else if (result.state === 'denied') {
          console.warn('Location permission denied. Please enable it in browser settings.');
        }

        // Optional: listen for changes (e.g., user changes permission in browser)
        result.onchange = () => {
          if (result.state === 'granted') {
            this.getLocation();
          }
        };
      });
    } else {
      // Fallback for older browsers
      this.getLocation();
    }
  }
  

  getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          this.registrationForm.patchValue({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude
          });
          console.log('Location obtained:', position.coords.latitude, position.coords.longitude);
          this.getAddressFromCoords(position.coords.latitude, position.coords.longitude).subscribe({
            next: (address) => {
              console.log('Address from coordinates:', address);
              this.registrationForm.patchValue({
                address: address.display_name,
                city: address.address.city || address.address.town || address.address.village,
                state: address.address.state,
                country: address.address.country,
                countryCode: address.address.country_code
              });
            },
            error: (err) => {
              console.error('Error fetching address:', err);
            }
          })
        },
        (error) => {
          console.error('Geolocation error:', error);
        }
      );
    } else {
      console.error('Geolocation is not supported by this browser.');
    }
  }
  

  options: string[] = ['country1', 'country2'];
  filteredOptions: any[] = [...this.options];

  onSearch(value: string): void {
    this.filteredOptions = this.options.filter(opt =>
      opt.toLowerCase().includes(value.toLowerCase())
    );
  }

  onChangeOfCountry(value: string): void {
    if (value && !this.options.includes(value)) {
      this.options.push(value);
      this.filteredOptions = [...this.options];
    }
  }

  compareFn = (o1: any, o2: any) => o1 === o2;

  getAddressFromCoords(lat: number, lon: number): Observable<any> {
    return this.http.get(`${this.nominatimUrl}?format=json&lat=${lat}&lon=${lon}&addressdetails=1`);
  }

}
