import { Component, inject, OnInit } from '@angular/core';
import { FormGroup, NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { apiService } from '../../services/apiService';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { NzModalRef } from 'ng-zorro-antd/modal';

@Component({
  selector: 'app-registration',
  imports: [NzInputModule, NzFormModule, NzCardModule, ReactiveFormsModule, RouterModule, NzButtonModule, NzSelectModule, NzDatePickerModule, NzIconModule],
  templateUrl: './registration.component.html',
  styleUrl: './registration.component.scss'
})
export class RegistrationComponent implements OnInit {
  // Form data
  private nominatimUrl = 'https://nominatim.openstreetmap.org/reverse';
  registrationForm!: FormGroup;
  private fb = inject(NonNullableFormBuilder)
  private apiService = inject(apiService)
  private http = inject(HttpClient)
  isEditable: boolean = false;
  passwordVisible = false;
  allowLocation: boolean = false;

  constructor() { }
  ngOnInit(): void {
    this.initilizeForm();
    const state: any = (history && (history.state || {})) || {};
    const userId = state?.id;

    if (userId) {
      this.isEditable = true;
      this.removePasswordValidation();
      this.loadUserForEdit(userId);
      return;
    }

    if (state?.prefill) {
      this.isEditable = !!state.edit;
      if (this.isEditable) {
        this.removePasswordValidation();
      }
      this.registrationForm.patchValue(state.prefill || {});
    }
  }

  private removePasswordValidation(): void {
    const passwdControl = this.registrationForm.get('password');
    if (passwdControl) {
      passwdControl.clearValidators();
      passwdControl.updateValueAndValidity();
    }
  }

  private loadUserForEdit(userId: number): void {
    this.apiService.getUserById(userId).subscribe({
      next: (res: any) => {
        const user = res?.body || res?.data || res;
        if (user) {
          this.registrationForm.patchValue(user);
          this.registrationForm.get('id')?.patchValue(user.id ?? userId);
        }
      },
      error: (err) => {
        console.error('Failed to load user for edit:', err);
      }
    });
  }

  initilizeForm() {
    this.registrationForm = this.fb.group({
      id: [null],                  // generated by Firebase or backend
      fullName: [null, Validators.compose([Validators.required, Validators.minLength(3)])],
      email: [null, Validators.compose([Validators.required, Validators.email])],
      phone: [null, Validators.compose([Validators.required, Validators.pattern('^[0-9]{10}$')])],
      password: [null, Validators.compose([Validators.required, Validators.minLength(6)])],
      bloodGroup: [null, Validators.required],         // e.g. 'A+', 'O-', etc.
      age: [null, Validators.compose([Validators.required, Validators.min(18), Validators.max(120)])],
      gender: [null, Validators.required],
      phonePrefix: ['+91', Validators.required],
      isAvailable: [true, Validators.required],  // switch toggle
      isActive: [true, Validators.required],  // switch toggle
      dob: [null, Validators.required],    // optional
      country: [{ value: null, disabled: true }, Validators.required],
      countryCode: [null],
      city: [{ value: null, disabled: true }, Validators.required],
      state: [{ value: null, disabled: true }, Validators.required],
      address: [null, Validators.required],
      role: ['ROLE_USER'],
      latitude: [null],
      longitude: [null],
      lastDonationDate: [null],
    });
  }

  submitForm() {
    console.log('Form submitted:', this.registrationForm);
    if (this.registrationForm?.valid) {
      const payload = this.registrationForm.getRawValue();
      if (this.isEditable && payload?.id) {
        this.apiService.editUser(payload).subscribe((res) => {
          console.log('Updated:', res);
          window.history.back();
        });
      } else {
        this.apiService.register(payload).subscribe((res) => {
          console.log(res);
          window.history.back();
        });
      }
    }
  }

  onChange(event: any) {
    console.log(event);
  }

  // Geolocation is opt-in so user can either fill data manually or allow current location.
  ngAfterViewInit() {
    if (this.isEditable) {
      return;
    }

    if (!navigator.permissions) {
      return;
    }

    navigator.permissions.query({ name: 'geolocation' as PermissionName }).then((result) => {
      if (result.state === 'granted' && this.allowLocation) {
        this.getLocation();
      }

      result.onchange = () => {
        if (result.state === 'granted' && this.allowLocation) {
          this.getLocation();
        }
      };
    });
  }

  useCurrentLocation(): void {
    this.allowLocation = true;
    this.getLocation();
  }

  getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          this.registrationForm.patchValue({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude
          });
          console.log('Location obtained:', position.coords.latitude, position.coords.longitude);
          this.getAddressFromCoords(position.coords.latitude, position.coords.longitude).subscribe({
            next: (address) => {
              console.log('Address from coordinates:', address);
              this.registrationForm.patchValue({
                address: address.display_name,
                city: address.address.city || address.address.town || address.address.village,
                state: address.address.state,
                country: address.address.country,
                countryCode: address.address.country_code
              });
            },
            error: (err) => {
              console.error('Error fetching address:', err);
            }
          })
        },
        (error) => {
          console.error('Geolocation error:', error);
        }
      );
    } else {
      console.error('Geolocation is not supported by this browser.');
    }
  }


  options: string[] = ['country1', 'country2'];
  filteredOptions: any[] = [...this.options];

  onSearch(value: string): void {
    this.filteredOptions = this.options.filter(opt =>
      opt.toLowerCase().includes(value.toLowerCase())
    );
  }

  onChangeOfCountry(value: string): void {
    if (value && !this.options.includes(value)) {
      this.options.push(value);
      this.filteredOptions = [...this.options];
    }
  }

  compareFn = (o1: any, o2: any) => o1 === o2;

  getAddressFromCoords(lat: number, lon: number): Observable<any> {
    return this.http.get(`${this.nominatimUrl}?format=json&lat=${lat}&lon=${lon}&addressdetails=1`);
  }

}
